### ISSUE TITLE
modify file loading to conform with creation of dseries from the command line

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dseries#6] opened 2015-06-10 21:34 UTC
See DynareTeam/dates#5

**Comment by stepan-a** [comment] 2015-09-10 14:06
The current behavior is not bizarre as you say (DynareTeam/dates#5), so I close this one also. In my experience (from users building datasets in Dynare using matlab scripts), the behavior you suggest would be the cause of a lot of trouble. I find it safer to force the user to have vectors of the same size.

**Closed by stepan-a** 2015-09-10 14:06 UTC
Labels: enhancement
